# -*- coding: utf-8 -*-

LANG_KEY = u"PT"
LANG_NATIVE_NAME = u"Português"

KWDS = {
"MSG_FORMAT_DEFAULT":       u"defeito: EMAIL [ASSUNTO] HIPERLIGAÇÃO E MENSAGEM ",
"MSG_FORMAT_WO_LINK":       u"sem_hiperligação: EMAIL [ASSUNTO] MENSAGEM",
"MSG_FORMAT_LINK_ONLY":     u"somente_hiperligação: EMAIL [ASSUNTO] HIPERLIGAÇÃO",
"MSG_FORMAT_SHORT":         u"curto: ASSUNTO",
"CHANGE_MSG_FORMAT":        u"/msg_format - Mudar formato da mensagem",
"CHANGE_SUBJ_RULES":        u"/subj_rules - Regras do assunto",
"CHANGE_BODY_RULES":        u"/body_rules - Regras do processamento",
"HIDE_KEYBOARD":            u"/hide - Esconder este teclado",
"GO_PAY":                   u"IR PARA O SISTEMA DE PAGAMENTO",
"CANCEL":                   u"Cancelar",
"REMOVE_RULES_BUTTON":      u"Remover todas as regras",
"CHECK_PAYMENT":            u"Rever estado do pagamento",
"CONFIRM_ORDER":            u"Confirmar pedido",
"SUCCESS_PAYMENT":          u"> Yay! O nome de utilizador {} é teu agora. De qualquer forma, podes receber todos os teus alias usando o comando /addresses",
"NOT_PAID":                 u"> Ainda não pago!",
"CANCELLED":                u"> Cancelado",
"ENTER_SUBJ":               u"> Introduza o assunto:",
"ENTER_SUBJ_ERR":           u"> Erro ao estabelecer assunto",
"ENTER_MSG":                u"> Introduza a mensagem:",
"ENTER_MSG_ERR":            u"> Erro ao estabelecer a mensagem. Tente de novo:",
"MSG_SENT":                 u"> Mensagem enviada",
"MSG_QUEUED":               u"> A mensagem foi colocada na fila de espera",
"MSG_NOT_SENT":             u"> Mensagem não foi enviada",
"MSG_ERROR_SENT":           u"> Erro no envio da mensagem",
"INCORR_SYMB":              u"> Simbolos incorretos! Escolha outro:",
"NAME_TAKEN":               u"> Este utilizador já está em uso! Escolha outro:",
"TRANS_ISSUE":              u"> Erro de transação. Contata o suporte: @adastreamer",
"PAY_CALL":                 u"> Feito! O teu endereço de e-mail está quase pronto. Tu só precisas de confirmar esta acção.",
"PAY_BUTTON":               u"Faça um pagamento",
"HI":                       u"> Olá, seja bem vindo! O endereço por defeito para este chat é: {}@etlgr.com {}",
"HI_POSTFIX":               u" (menos é uma parte do endereço)",
"ENTER_SENDER":             u"> Introduz o endereço de onde queres mandar a mensagem:",
"ENTER_SENDER_WRONG":       u"> Este não é o teu endereço. Tente de novo:",
"ENTER_EMAIL":              u"> Introduza o(s) endereço(s) dos teu(s) destinatário(s):",
"ENTER_EMAIL_ERR":          u"> Erro ao estabelecer os e-mail(s). Tu podes escolher até 5 destinatários. Tente de novo.",
"CHOOSE_NAME":              u"> Escolha o teu utilizador (ex. andre):",
"ADDRESSES_LIST_BASE":      u"> Os teus endereços:",
"CHOOSE_ACTION":            u"> Escolha a acção:",
"CHOOSE_LANG":              u"> Escolha a Língua/Idioma:",
"GET_ADDRESS":              u"/start - Obter os endereços por defeito",
"CHANGE_LANG":              u"/lang - Muda a Língua/Idioma",
"SEND_MSG":                 u"/send - Enviar uma mensagem",
"REGISTER_OWN":             u"/register - Obter um endereço pessoal",
"GET_ADDRESSES":            u"/addresses - Teus endereços",
"CHOOSE_RELEASE_ADDRESS":   u"> Escolher endereço para libertar:",
"NO_ADDRESS_TO_RELEASE":    u"> Tu não tens endereços. Tu deves reservar um escrevendo o comando /register.",
"RELEASE":                  u"/release - Libertar o teu endereço.",
"WRONG_RELEASE_ADDRESS":    u"> Endereço errado. Tente de novo:",
"RELEASED_CHOOSE_ACTION":   u"> Libertado! Escolha a acção:",
"KEYBOARD_HIDDEN":          u"> Teclado está escondido. Tu podes também, mostrar todas as acções escrevendo o comando /start",
"CHOOSE_MSG_FORMAT":        u"> Escolhe o formato das mensagens recebidas:",
"MSG_FORMAT_CHANGED":       u"> Formato das mensagens recebidas foi alterado",
"MSG_RULES_CHANGED":        u"> Regras de processamento foram alteradas",
"MSG_RULES_REMOVED":        u"> Regras de processamento foram elimanadas",
"CHANGE_SUBJ_RULES_MSG":    u"Tu podes alterar as regras de processamento do assunto das mensagens. Tu podes alterar a $string1 com a $string2. Por favor introduza estes textos por linha. (Usando o novo espaçamento de linha). Por exemplo: \nFoo\nBar\n\nSe tu introduzires unicamente uma linha, este subtexto vai ser removido.\nTambém podes usar expressões regulares.",
"CHANGE_BODY_RULES_MSG":    u"Tu podes alterar as regras de processamento do corpo das mensagens. Tu podes alterar a $string1 com a $string2. Por favor introduza estes textos por linha. (Usando o novo espaçamento de linha) . For example: \nFoo\nBar\n\nSe tu introduzires unicamente uma linha, este subtexto vai ser removido.\nTambém podes usar expressões regulares.",
"CHANGE_SUBJ_RULES_ERROR":  u"Erro ao estabelecer as regras do assunto.Tens a certeza que inseriste 2 linhas?Tenta de novo ou cancela:",
"CHANGE_BODY_RULES_ERROR":  u"Erro ao estabelecer as regras do corpo.Tens a certeza que inseriste 2 linhas?Tenta de novo ou cancela:",
}
